# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
#
# Remote write configuration (for Graphite, OpenTSDB, or InfluxDB).
remote_write:
{% for item in emq_endpoints %}
  - url: "http://{{item}}:8086/api/v1/prom/write?u=paul&p=foo&db=sxiot"
{% endfor %}
# # Remote read configuration (for InfluxDB only at the moment).
remote_read:
{% for item in emq_endpoints %}
  - url: "http://{{item}}:8086/api/v1/prom/read?u=paul&p=foo&db=sxiot"
{% endfor %}
