# python -m SimpleHTTPServer 8000
- name: common config
  hosts: all

  tasks:
  - name: Disable selinux
    selinux:
      state: disabled

  - name: Disable temp selinux
    shell: setenforce 0
    ignore_errors: yes

  - name: mkdir the common config dir
    file:
      path: /etc/sxiot
      state: directory
      mode: 0755

  - name: write the common config file
    template: src=templates/sxiot.conf.j2 dest=/etc/sxiot/sxiot.conf

  - name: clean repo
    shell: rm -rf /etc/yum.repos.d/*

  - name: write the repo file
    template: src=templates/sxiot.repo.j2 dest=/etc/yum.repos.d/sxiot.repo

  - name: clean all
    shell: yum clean all

  - name: makecache
    shell: yum makecache

- name: etcd setup
  hosts: uapi
  tasks:
  - name: Install etcd
    yum: name=etcd state=latest update_cache=yes

  - name: Restart etcd
    service: name=etcd enabled=true state=restarted

- name: emq setup
  hosts: emq
  gather_facts: no

  roles:
    - role: emq
      uapi_ip: 127.0.0.1

- name: sxiot-uapi setup
  hosts: uapi
  gather_facts: no
  vars:
    emq_endpoints: []

  pre_tasks:

    - name: Set emq endpoints
      set_fact:
        emq_endpoints: "{{ emq_endpoints }} + ['{{ hostvars[item].ansible_ssh_host }}']"
      with_items: "{{ groups['emq'] }}"

  roles:
    - role: sxiot-uapi